name: if-condition

on:
  workflow_dispatch:
    inputs:
      select-env:
        description: 'ENV selection'
        required: true
        default: 'Please-Select-ENV'
        type: choice
        options:
          - dev
          - UAT
          - Prod

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - name: step1 - dev
        if: ${{ github.event.inputs.select-env == 'dev' }}
        run: echo "Done in dev"

      - name: step2 - UAT
        if: ${{ github.event.inputs.select-env == 'UAT' }}
        run: echo "Done in UAT"

      - name: step3 - Prod
        if: ${{ github.event.inputs.select-env == 'Prod' }}
        run: echo "Done in Prod"
